[package]
name = "pdflib"
version = "0.1.0"
authors = ["Hroi Sigurdsson <hroi@asdf.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdflib-sys = { path = "./pdflib-sys" }
libc = "0.2.71"
